spring:
  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
  #        format_sql: true

  config:
    activate:
      on-profile: test