spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-61.railway.app:7470/railway
    username: postgres
    password: ASFsw2CHeA9LmLNa8KYA

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  security.basic.enabled: false

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

server:
  port: 443
  servlet:
    session:
      timeout: 30
#  ssl:
#    enabled: true
#    key-alias: ayokeystore
#    key-store: ayokeystore.pkcs12
#    key-store-password: '123456'
#    key-password: '123456'
#    trust-store: ayotrust.pkcs12
#    trust-store-password: '123456'