spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pcs.pah.kr:1101/daejeon
    username: postgres
    password: daejeon
  profiles:
    active: real
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#        show_sql: true
#        format_sql: true

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        show_sql: true
#  #        format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
server:
  port: 1100
  servlet:
    session:
      timeout: 43200
      cookie:
        secure: true
        same-site: none
        max-age: 3600
#  ssl:
#    enabled: true
#    key-alias: ayokeystore
#    key-store: ayokeystore.pkcs12
#    key-store-password: '123456'
#    key-password: '123456'
#    trust-store: ayotrust.pkcs12
#    trust-store-password: '123456'