spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://containers-us-west-129.railway.app:6747/railway
    username: postgres
    password: pU8DtkaPac3IrrVNRkiP

  profiles:
    active: real

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#        show_sql: true
#        format_sql: true

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 80
  servlet:
    session:
      timeout: 43200
      cookie:
        secure: true
        same-site: none
        max-age: 3600

#  ssl:
#    enabled: true
#    key-alias: ayokeystore
#    key-store: ayokeystore.pkcs12
#    key-store-password: '123456'
#    key-password: '123456'
#    trust-store: ayotrust.pkcs12
#    trust-store-password: '123456'